# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clutcher/generated.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainFrame(object):
    def setupUi(self, MainFrame):
        MainFrame.setObjectName("MainFrame")
        MainFrame.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainFrame)
        self.centralwidget.setObjectName("centralwidget")
        MainFrame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainFrame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainFrame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainFrame)
        self.statusbar.setObjectName("statusbar")
        MainFrame.setStatusBar(self.statusbar)
        self.actionAdd_File = QtWidgets.QAction(MainFrame)
        self.actionAdd_File.setObjectName("actionAdd_File")
        self.actionExit = QtWidgets.QAction(MainFrame)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionAdd_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainFrame)
        self.actionExit.destroyed['QObject*'].connect(MainFrame.close)
        QtCore.QMetaObject.connectSlotsByName(MainFrame)

    def retranslateUi(self, MainFrame):
        _translate = QtCore.QCoreApplication.translate
        MainFrame.setWindowTitle(_translate("MainFrame", "Clutcher"))
        self.menuFile.setTitle(_translate("MainFrame", "File"))
        self.actionAdd_File.setText(_translate("MainFrame", "&Open"))
        self.actionExit.setText(_translate("MainFrame", "&Exit"))
        self.actionExit.setShortcut(_translate("MainFrame", "Ctrl+Q"))
